config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/:page_id' => 'static_pages#view'
  get '/' => 'static_pages#home'
 
    resources :categories
  get 'categories/:id/delete' => 'categories#delete', :as => :categories_delete

  resources :products
  get 'products/:id/delete' => 'products#delete', :as => :products_delete

  

  devise_for :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user! 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

   def new
    @category = Category.new 
  end
  
  def create
     @category = Category.new(category_params)
    if @category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

 def edit
    @category = Category.find(params[:id])
  end
  
def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(:action => 'show', :id => @category.id)
    else
      render('index')
    end
end

 def delete
    @category = Category.find(params[:id])
  end
  
def destroy
    Category.find(params[:id]).destroy
    redirect_to(:action => 'index')
end
  

  private
  def category_params
    params.require(:category).permit(:name, :thumburl)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

   def new
    @product = Product.new 
  end
  
  def create
     @product = Product.new(product_params)
    if @product.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to(:action => 'show', :id => @product.id)
    else
      render('index')
    end
  end

  def delete
    @product = Product.find(params[:id])
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end
  
 private
 def product_params
  params.require(:product).permit(:product_name, :description, :price, :thumburl)
 end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_filter :page_id

    def view
      render "static_pages/#{@page_id}"
    end

    def page_id
      @page_id = params[:page_id]
    end

end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <div class="name">

  </div>
  <div class="thumburl">

  </div>
  <div class="actions">

  </div>
  <div class="categories">
  	<%= f.text_field :name %>
  	<%= f.url_field :thumburl %>
  	<%= f.submit %>
  </div>
<% end %>

app/views/categories/delete.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Thumburl:</strong>
  <%= @category.thumburl %>
</p>

<%= link_to "Delete", categories_delete_path(:id => @category.id) %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.html.erb
<%= render 'shared/topnav' %>

<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

<%= render 'shared/footer' %>

app/views/categories/index.html.erb
<%= render 'shared/topnav' %>

<div class="categories">
      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <h2>Testing</h2>
            <p>Explore our latest categories from around the world.</p>
          </div>
          <div class="col-md-8">
            <% @categories.in_groups_of(3).each do |categories| %>
              <% categories.select! {|x| !x.nil?} %>
              <div class='row'>
                <% categories.each do |category| %>
                  <div class='col-md-4'>
                    <div class="thumbnail">
                        <img src= <%= category.thumburl %> >
                        <div class="caption">
                          <p align="center" class="listing-title"><%= category.name %></p>
                          <span><%= link_to "Edit", edit_category_path(category.id), :class => "btn btn-default", :role => "button"%></span>
                          <span><%= link_to 'Show', category, :class => "btn btn-default"%></span>
                          <span><%= link_to 'Delete', categories_delete_path(:id => category.id) , :class => "btn btn-default"%></span>
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>
            <% end %>

          </div>
        </div>

      </div>
    </div>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
<!--
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <div class="thumbnail">
           <img src= <%=category.thumburl %> >
        <div>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>-->

<%= link_to 'New Category', new_category_path %>

<%= render 'shared/footer' %>

app/views/categories/new.html.erb
<%= render 'shared/topnav' %>

<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

<%= render 'shared/footer' %>

app/views/categories/show.html.erb
<%= render 'shared/topnav' %>
<br>
<br>
<br>

<h1>Listing products</h1>

<% @products.in_groups_of(3).each do |products| %>
  <% products.select! {|x| !x.nil?} %>
  <div class='row'>
    <% products.each do |product| %>
      <div class='col-md-4'>
        <div class="thumbnail">
            <img src= <%= product.thumburl %> >
            <div class="caption">
              <span class="listing-title"><%= product.product_name %></span>
              <span class="listing-desc"><%= product.description %></span>
              <span class="listing-price"><%= number_to_currency(product.price) %></span>
              <span><%= link_to "Edit", edit_product_path(product.id) %></span>
              <span><%= link_to "Delete", products_delete_path(:id => product.id) %></span>
            </div>
          </div>
      </div>
    <% end %>
  </div>
<% end %>
<br>

<%= link_to 'New Product', new_product_path %>



<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QA in Odessa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/topnav' %>

<div class="container">
  <div class="jumbotron" style="background-image: url(http://4.firepic.org/4/images/2014-12/23/nik5jlbi6ltl.jpg)">
    <h1>QA in Odessa</h1>
      <p>All what you want to know about Software Testing</p>
      <p><a class="btn btn-lg btn-primary" role="button" href="#">What is Software Testing? »</a></p>
  </div>
</div>


<div class="trending">
  <div class="container">
    <h2>Necessary knowledge</h2>
    <p>What you have to know to became Software Tester?</p>
    <div class="row trending-listing">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/swkx0lkv8bkc.gif">
          <div class="caption">
            <span class="listing-title">Quality Assurance</span>
          </div>
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/zwu93whjh6a6.gif">
          <div class="caption">
            <span class="listing-title">Networks</span>
          </div>
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/fafo2q7c8c7z.gif">
          <div class="caption">
            <span class="listing-title">Databases</span>
          </div>
        </div>
      </div>
       <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/2pkejt9hjpm5.gif">
          <div class="caption">
            <span class="listing-title">Programming</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<%= f.text_field :product_name %>
	<%= f.text_field :description %>
	<%= f.text_field :price %>
	<%= f.url_field :thumburl %>

  <div class="product_name">

  </div>
  <div class="description">

  </div>
  <div class="price">

  </div>
  <div class="thumburl">

  </div>
  <div class="actions">
		<%= f.submit %>
  </div>
<% end %>

app/views/products/delete.html.erb
<p>
  <strong>Product name:</strong>
	<%= @product.product_name %>
</p>

<p>
  <strong>Description:</strong>
	<%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
	<%= @product.price %>
</p>

<p>
  <strong>Thumburl:</strong>
	<%= @product.thumburl %>
</p>

<%= link_to 'Delete', products_delete_path(:id => @product.id) %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.html.erb
<%= render 'shared/topnav' %>

<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

<%= render 'shared/footer' %>

app/views/products/index.html.erb
<%= render 'shared/topnav' %>
<br>
<br>
<br>

<h1>Listing products</h1>

<% @products.in_groups_of(3).each do |products| %>
  <% products.select! {|x| !x.nil?} %>
  <div class='row'>
    <% products.each do |product| %>
      <div class='col-md-4'>
        <div class="thumbnail">
            <img src= <%= product.thumburl %> >
            <div class="caption">
              <span class="listing-title"><%= product.product_name %></span>
              <span class="listing-desc"><%= product.description %></span>
              <span class="listing-price"><%= number_to_currency(product.price) %></span>
              <span><%= link_to "Edit", edit_product_path(product.id) %></span>
              <span><%= link_to "Delete", products_delete_path(:id => product.id) %></span>
            </div>
          </div>
      </div>
    <% end %>
  </div>
<% end %>
<br>

<%= link_to 'New Product', new_product_path %>



<%= render 'shared/footer' %>

app/views/products/new.html.erb
<%= render 'shared/topnav' %>

<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

<%= render 'shared/footer' %>

app/views/products/show.html.erb
<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Description:</strong>
	<%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
<%= @product.price %>
</p>

<p>
  <strong>Thumburl:</strong>
<%= @product.thumburl %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <span class="navbar-text pull-right">
      (c) Cmorodinka
    </span>
  </div>
</div>

app/views/shared/_topnav.html.erb
<div class="container">
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">QA in Odessa</a>
		</div>
	<div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<li><a href="/static_pages/home">Home</a></li>
			<li><a href="/static_pages/about">About</a></li>
			<li><a href="/static_pages/contact">Contact</a></li>
			<li class="dropdown"><a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">More<span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="/static_pages/qa_manual">QA Manual</a></li>
					<li><a href="/static_pages/qa_automation">QA Automation</a></li>
					<li class="divider"></li>
					<li class="dropdown-header">Other</li>
					<li><a href="/static_pages/how">How to become QA</a></li>
					<li><a href="/static_pages/faq">FAQ</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav pull-right">
			<form class="navbar-form pull-right">
                <% if user_signed_in? %>
              		Logged in as <strong> <%= current_user.email %> </strong>
            		<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn-default" %>
            	<% else %>
              		<%= link_to "Sign up", new_user_registration_path, :class => "btn btn-default" %>
              		<%= link_to "Sign in", new_user_session_path, :class => "btn btn-default" %>
            	<% end %>
            </form>
         </ul> 	
       </div>
	</div>
</nav>	 
</div>

app/views/static_pages/about.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <h2>What is quality assurance (QA)?</h2>
    <h3>Definition from WhatIs.com</h3>
    <p>In developing products and services, quality assurance is any systematic process of checking to see whether a product or service being developed is meeting specified requirements. Many companies have a separate department devoted to quality assurance. A quality assurance system is said to increase customer confidence and a company's credibility, to improve work processes and efficiency, and to enable a company to better compete with others. Quality assurance was initially introduced in World War II when munitions were inspected and tested for defects after they were made. Today's quality assurance systems emphasize catching defects before they get into the final product.</p>
	<p>ISO 9000 is an international standard that many companies use to ensure that their quality assurance system is in place and effective. Conformance to ISO 9000 is said to guarantee that a company delivers quality products and services. To follow ISO 9000, a company's management team decides quality assurance policies and objectives. Next, the company or an external consultant formally writes down the company's policies and requirements and how the staff can implement the quality assurance system. Once this guideline is in place and the quality assurance procedures are implemented, an outside assessor examines the company's quality assurance system to make sure it complies with ISO 9000. A detailed report describes the parts of the standard the company missed, and the company agrees to correct any problems within a specific time. Once the problems are corrected, the company is certified as in conformance with the standard.</p>
    
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/contact.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <p><a href="http://en.wikipedia.org/wiki/Software_quality_assurance" target="_blank">Wikipedia</a></p>
    </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/databases.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <h2>Databases</h2>
    <h3>Databases as part of life</h3>
    <p>SQL and/or with MySQL will greatly depend on the project and/or the company with whom you hope to work. SQL skills are one aspect of Software Testing that focuses specially on technology. (c) <a href="http://sqa.stackexchange.com/users/1455/chris-kenst" target="_blank">Chris Kenst</a></p>
    <div class="row trending-listing">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/fafo2q7c8c7z.gif">
          <div class="caption">
            <span class="listing-title">Databases</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/faq.html.erb
<%= render 'shared/topnav' %>

<div class="container">
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Software Quality Assurance
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        A planned and systematic pattern of all actions necessary to provide adequate confidence that an item or product conforms to established technical requirements. A set of activities designed to evaluate the process by which products are developed or manufactured. 
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          What's difference between client/server and Web Application?
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Client/server based is any application architecture where one server application and one or many client applications are involved like your mail server and MS outlook Express, it can be a web application as well, where the Web Application is a kind of client server application that is hosted on the web server and accessed over the internet or interanet. There are lots of things that differs between testing of the two type above and cann't be posted in one post but you can look into the data flow, communication and servside variable like session and security etc 
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Software Quality Assurance Activities
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
      	<li>Application of Technical Methods (Employing proper methods and tools for developing software)</li>
      	<li>Conduct of Formal Technical Review (FTR)</li>
      	<li>Testing of Software</li>
      	<li>Enforcement of Standards (Customer imposed standards or management imposed standards)</li>
      	<li>Control of Change (Assess the need for change, document the change)</li>
      	<li>Measurement (Software Metrics to measure the quality, quantifiable)</li>
      	<li>Records Keeping and Recording (Documentation, reviewed, change control etc. i.e. benefits of docs)</li>
   	  </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          What is good code?
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        A good code is code that works, is free of bugs and is readable and maintainable. Organizations usually have coding standards all developers should adhere to, but every programmer and software engineer has different ideas about what is best and what are too many or too few rules. We need to keep in mind that excessive use of rules can stifle both productivity and creativity. Peer reviews and code analysis tools can be used to check for problems and enforce standards.
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          How do you perform integration testing?
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <div class="panel-body">
        To perform integration testing, first, all unit testing has to be completed. Upon completion of unit testing, integration testing begins. Integration testing is black box testing. The purpose of integration testing is to ensure distinct components of the application still work in accordance to customer requirements. Test cases are developed with the express purpose of exercising the interfaces between the components. This activity is carried out by the test team. Integration testing is considered complete, when actual results and expected results are either in line or differences are explainable, or acceptable, based on client input. 
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          What is retesting? 
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <div class="panel-body">
        Retesting is usually equated with regression testing (see above) but it is different in that is follows a specific fix--such as a bug fix--and is very narrow in focus (as opposed to testing entire application again in a regression test). A product should never be released after any change has been applied to the code, with only retesting of the bug fix, and without a regression test. 
      </div>
    </div>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSeven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
       	When do we prepare a Test Plan? 
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
      <div class="panel-body">
        For four or five features at once, a single plan is fine. Write new test cases rather than new test plans. Write test plans for two very different purposes. Sometimes the test plan is a product; sometimes it's a tool. 
      </div>
    </div>
  </div>
</div>
</div>

<%= render 'shared/footer' %>

app/views/static_pages/home.html.erb
<%= render 'shared/topnav' %>

<div class="container">
  <div class="jumbotron" style="background-image: url(http://4.firepic.org/4/images/2014-12/23/nik5jlbi6ltl.jpg)">
    <h1>QA in Odessa</h1>
      <p>All what you want to know about Software Testing</p>
      <p><a class="btn btn-lg btn-primary" role="button" href="/static_pages/how">What is Software Testing? »</a></p>
  </div>
</div>


<div class="trending">
  <div class="container">
    <h2>Necessary knowledge</h2>
    <p>What do you have to know to become Software Tester?</p>
    <div class="row trending-listing">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <a href="/static_pages/quality_assurance">
          <img src="http://2.firepic.org/2/images/2014-12/23/swkx0lkv8bkc.gif">
          <div class="caption">
            <span class="listing-title">Quality Assurance</span>
          </div>
          </a>  
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <a href="/static_pages/networks">
          <img src="http://2.firepic.org/2/images/2014-12/23/zwu93whjh6a6.gif">
          <div class="caption">
            <span class="listing-title">Networks</span>
          </div>
          </a> 
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <a href="/static_pages/databases">
          <img src="http://2.firepic.org/2/images/2014-12/23/fafo2q7c8c7z.gif">
          <div class="caption">
            <span class="listing-title">Databases</span>
          </div>
          </a> 
        </div>
      </div>
       <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <a href="/static_pages/programming">
          <img src="http://2.firepic.org/2/images/2014-12/23/2pkejt9hjpm5.gif">
          <div class="caption">
            <span class="listing-title">Programming</span>
          </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/how.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <h2>How to become QA</h2>
    <p>The QA Tester is the heart and soul of the software development process. Each project team member has their role to play; each has their own unique challenges. The successful Quality Assurance Tester gains respect by holding the bar high, carrying the Standard, and being the champion for the level of quality (product and otherwise) throughout the organization.</p>
	<p>Although not often granted the authority to officially prevent software from shipping, the tester is nonetheless in the best position to know the current project state at any given time. The final “go / no-go” call to ship or not may be left to the QA Lead, or the QA Manager, or perhaps even a project manager, but the input they receive from the tester is critical.</p>
	<p>Is becoming a Software Quality Assurance Tester easy? Actually yes, it is fairly easy. There are many entry-level positions open all the time in the testing arm of the software industry. Even during times of economic slowdown, finding an open slot to fill is not really the hard part. With software development occurring all over the world at an increasing rate, there are now and will continue to be software testing positions open that need to be filled.</p>
	<p>The “hard part” is keeping the job once you have been hired. Many companies fill their available QA Tester positions with temps. These hires are most often managed on a per-project basis. Although by no means the most efficient (or effective) way to manage testing, this allows a company to rid itself of temps who cannot cut it as a QA Tester as soon as the project is complete (if not sooner).</p>
	  
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/networks.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <h2>Networks</h2>
    <h3>Is it necessary?</h3>
    <p>Good testers have critical thinking, analytical, and investigative skills. They understand risk and have a deep understanding where bugs tend to hide. They have excellent communication skills. Most good testers have some measure of technical skill such as system administration, databases, networks, etc. that lends itself to gray box testing. (c) <a href="http://testobsessed.com/about.html" target="_blank">Elisabeth Hendrickson</a></p>
    <div class="row trending-listing">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/zwu93whjh6a6.gif">
          <div class="caption">
            <span class="listing-title">Networks</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

<%= render 'shared/footer' %>

app/views/static_pages/programming.html.erb
<%= render 'shared/topnav' %>

<div class="trending">
  <div class="container">
    <h2>Programming</h2>
    <h3>Do Testers Have to Write Code?</h3>
    <p>This question you ask is one on which many traditional testers depend for career survival. 
    Short answer is maybe. You are right to identify the work flow as an issue, but the work flow is simple compared with training for programming and development. Making testers into programmers may be a bridge too far. There are many other skills that have closer affinity to your testers' current skill set.
	I think there is a role for Software Test Engineers, but two new creatures are on the scene, the Test Driven Developer and the Software Development Engineer in Test who will take over a lot of turf that used to belong to the STE. (c) <a href="http://programmers.stackexchange.com/users/61659/developerdon" target="_blank">DeveloperDon</a></p>
    <div class="row trending-listing">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <img src="http://2.firepic.org/2/images/2014-12/23/2pkejt9hjpm5.gif">
          <div class="caption">
            <span class="listing-title">Programming</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

<%= render 'shared/footer' %>